In [1]:
import numpy as np

## Creating arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

## Multidimensional arrays

In [7]:
a = np.array([2, 3, 4, 5, 6])

In [8]:
a[2]

4

In [9]:
a[2] = 10

In [10]:
a

array([ 2,  3, 10,  5,  6])

In [12]:
np.arange(3, 10, 0.5)

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. ,
       9.5])

In [15]:
np.linspace(0,100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multidemensional arrays

In [16]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [18]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
n[0, 1] = 20

In [21]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [23]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [24]:
n[:, 1]

array([20,  5,  1])

## Random generated arrays

In [26]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [27]:
np.random.seed(2)
np.random.randn(5, 2)


array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [28]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [29]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [35]:
b = (10 + (a * 2)) * 100

In [36]:
a + b

array([1000, 1201, 1402, 1603, 1804])

## Comparison operations

In [37]:
a >= 2

array([False, False,  True,  True,  True])

In [39]:
a[a < b]

array([0, 1, 2, 3, 4])

## Summarizing  operations

In [40]:
a

array([0, 1, 2, 3, 4])

In [41]:
a.min()

0

In [42]:
a.max()

4

In [43]:
a.mean()

2.0

In [44]:
a.std()

1.4142135623730951

## Vector operations

In [45]:
u = np.array([2, 4, 5, 6])

In [46]:
v = np.array([1, 0, 0, 2])

In [47]:
u + v

array([3, 4, 5, 8])

## Multiplication

- Vector-vector multiplication
- Matrix-vector multiplication
- Matrix-matrix multiplication

### Vector-Vector Multiplication (dot product)

In [50]:
u = np.array([2, 4, 5, 6])
2 * u

array([ 4,  8, 10, 12])

In [51]:
v = np.array([1, 0, 0, 2])

In [52]:
u + v

array([3, 4, 5, 8])

In [53]:
u * v

array([ 2,  0,  0, 12])

$$
\begin{bmatrix}
2 & 4 & 5 & 6
\end{bmatrix}
$$

$$
\begin{bmatrix}
1 \\
0 \\
0 \\
2 \\
\end{bmatrix}
$$

Multiplication

In [54]:
v.shape[0]

4

In [55]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [56]:
vector_vector_multiplication(u, v)

14.0

In [57]:
# Using numpy
u.dot(v)

14

## Matrix vector multiplication

In [58]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [59]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [60]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    return result

In [61]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [62]:
U.dot(v)

array([14,  5,  5])

In [68]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

In [70]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:,i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [71]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [72]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix

The number one of matrix, every matrix multiply by identity matrix will return the same matrix

In [74]:
I = np.eye(3)

In [75]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [78]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse

In [79]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [80]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

In [82]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])